# Generated by Django 3.2.25 on 2026-02-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('farmer', models.CharField(max_length=191)),
                ('national_id', models.IntegerField(blank=True, null=True)),
                ('vehicle_no', models.CharField(max_length=191)),
                ('gnr', models.CharField(max_length=191)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('crates', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateField()),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state_id', models.IntegerField()),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sortname', models.CharField(max_length=255)),
                ('phonecode', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('national_id', models.IntegerField()),
                ('phone', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'farmers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'fruits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gnr', models.CharField(blank=True, max_length=191, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=191, null=True)),
                ('cartons', models.CharField(blank=True, max_length=191, null=True)),
                ('fruit_type', models.CharField(blank=True, max_length=191, null=True)),
                ('buying_price', models.CharField(blank=True, max_length=191, null=True)),
                ('selling_price', models.CharField(blank=True, max_length=191, null=True)),
                ('framlil_total', models.IntegerField(blank=True, null=True)),
                ('supplier_total', models.IntegerField(blank=True, null=True)),
                ('profit', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rejects',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('farmer', models.CharField(max_length=191)),
                ('vehicle_no', models.CharField(max_length=191)),
                ('rejects', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rejects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gnr', models.CharField(blank=True, max_length=191, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=191, null=True)),
                ('cartons', models.CharField(blank=True, max_length=191, null=True)),
                ('buying_price', models.CharField(blank=True, max_length=191, null=True)),
                ('selling_price', models.CharField(blank=True, max_length=191, null=True)),
                ('framlil_total', models.IntegerField()),
                ('supplier_total', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('is_finalized', models.BooleanField(default=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sizes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country_id', models.IntegerField()),
            ],
            options={
                'db_table': 'states',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('email', models.CharField(max_length=191, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=191)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weights',
                'managed': False,
            },
        ),
    ]
