# Generated by Django 3.2.25 on 2026-02-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gnr', models.CharField(blank=True, max_length=191, null=True)),
                ('cartons', models.IntegerField(default=0)),
                ('buying_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('framlil_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('supplier_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_finalized', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
