# Generated by Django 3.2.25 on 2026-03-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260225_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruits',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='prices',
            options={'managed': True},
        ),
    ]
