# Generated by Django 3.2.25 on 2026-03-04 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20260304_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='fruit',
            field=models.ForeignKey(blank=True, db_column='fruit_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fruits'),
        ),
        migrations.AlterField(
            model_name='fruits',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fruits',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prices',
            name='buying_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prices',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prices',
            name='selling_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prices',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
