# Generated by Django 3.2.25 on 2026-03-11 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20260304_1307'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prices',
            unique_together={('fruit', 'buying_price', 'selling_price')},
        ),
    ]
